In [3]:
%matplotlib inline
import numpy as np
import pandas as pd

#import viz # curriculum example visualizations

np.random.seed(29)




In [4]:
# Exercises

# 1 How likely is it that you roll doubles when rolling two dice?

n_trials = 1_000
n_dice = 2
rolls = pd.DataFrame(np.random.randint(0, 2, size = (n_trials, n_dice)) )
rolls



0  1
0    1  1
1    0  1
2    0  0
3    0  1
4    1  0
..  .. ..
995  1  1
996  1  1
997  0  1
998  1  0
999  0  0

[1000 rows x 2 columns]

In [5]:
# 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? 
# What is the probability of getting more than 3 heads?

outcomes = ['H','T']

n_simulations = 1_000
n_trials = 8 

coinflips = np.random.choice(outcomes, (n_simulations, n_trials))
head_count = (coinflips == 'H').sum(axis=1)

(head_count >= 3).mean()


0.856

In [20]:
# 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup.
#Assuming that Codeup randomly selects an alumni to put on a billboard, 
#what are the odds that the two billboards I drive past both have data science students on them?

n_simulation = 10_000
n_trial = 2
billboards = np.random.choice(([1,0,0,0]),(n_simulation, n_trial))
#results = np.random.choice((([1,0,0,0]),(n_simulation, n_trials)))

In [21]:
billboards

array([[0, 0],
       [0, 1],
       [0, 0],
       ...,
       [0, 0],
       [1, 1],
       [1, 1]])

In [22]:
billboards = billboards.sum(axis = 1) == 2
billboards

array([False, False, False, ..., False,  True,  True])

In [23]:
billboards.mean()

0.0587

In [67]:
# 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the 
#snack vending machine. If on monday the machine is restocked with 17 poptart packages, 
#how likely is it that I will be able to buy some poptarts on Friday afternoon? 
#(Remember, if you have mean and standard deviation, use the np.random.normal) 
#You'll need to make a judgement call on how to handle some of your values



n_poptart_packages_restocked = 17
avg_poptart_packages_purchased = 3
std_dev = 1.5
n_days = 4

poptart_packages = np. random.normal(avg_poptart_packages_purchased,std_dev, size = (n_trials, n_days)).round()
poptart_packages = np.where(poptart_packages < 1, 1, poptart_packages)
poptarts

array([[3., 3., 3., 3.],
       [6., 2., 2., 2.],
       [5., 2., 3., 3.],
       [2., 1., 2., 0.],
       [3., 4., 2., 5.],
       [3., 3., 2., 4.],
       [2., 6., 2., 5.],
       [3., 2., 3., 2.]])

In [68]:
at_least_one_poptart_remaining = poptarts. sum(axis= 1)<= n_poptarts_restocked - 1
at_least_one_poptart_remaining.mean( )

1.0

In [88]:
#5. Compare Heights:

# Men have an average height of 178 cm and standard deviation of 8cm.
# Women have a mean of 170, sd = 6cm.
# Since you have means and standard deviations, you can use np.random.normal to generate observations.
# If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

avg_height_of_men = 178
std_dev_men = 8
avg_height_of_women = 170
std_dev_women = 6

avg_height_of_men = np.random.normal(avg_height_of_men, std_dev_men, size = n_trials)
avg_height_of_women = np.random.normal(avg_height_of_women, std_dev_women, size = n_trials)

(avg_height_of_women>avg_height_of_men).mean()


0.125

In [44]:
#6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download
#is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, 
#no one has an installation issue? 100 students?

#What is the probability that we observe an installation issue within the first 150 students that download anaconda?

#How likely is it that 450 students all download anaconda without an issue?


In [36]:
# What are the odds that after having 50 students download anaconda, no one has an installation issue?

download_p_fail = 1/250
download_p_pass = 249/250
choice = [0,1]
sample = 50
n_sim = 10_000
array = np.random.choice(choice,p=[download_p_pass,download_p_fail],size = (n_sim, sample))
anaconda_installation = pd.DataFrame(array)
anaconda_installation.head()

0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  46  \
0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
3   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
4   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   

   47  48  49  
0   0   0   0  
1   0   0   0  
2   0   0   0  
3   0   0   0  
4   0   0   0  

[5 rows x 50 columns]

In [37]:

(anaconda_installation.sum(axis = 1) == 0).mean()

0.8144

In [38]:
# What are the odds that after having 100 students download anaconda, no one has an installation issue?


download_p_fail = 1/250
download_p_pass = 249/250
choice = [0,1]
sample = 100
n_sim = 10_000
array = np.random.choice(choice,p=[download_p_pass,download_p_fail],size = (n_sim, sample))
anaconda_installation = pd.DataFrame(array)
anaconda_installation.head()

0   1   2   3   4   5   6   7   8   9   ...  90  91  92  93  94  95  96  \
0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
3   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
4   0   0   0   0   1   0   0   0   0   0  ...   0   0   0   0   0   0   0   

   97  98  99  
0   0   0   0  
1   0   0   0  
2   0   0   0  
3   0   0   0  
4   0   0   0  

[5 rows x 100 columns]

In [39]:

(anaconda_installation.sum(axis = 1) == 0).mean()

0.6771

In [40]:
#What is the probability that we observe an installation issue within the first 150 students that download anaconda?

download_p_fail = 1/250
download_p_pass = 249/250
choice = [0,1]
sample = 150
n_sim = 10_000
array = np.random.choice(choice,p=[download_p_pass,download_p_fail],size = (n_sim, sample))
anaconda_installation = pd.DataFrame(array)
anaconda_installation.head()

0    1    2    3    4    5    6    7    8    9    ...  140  141  142  143  \
0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
1    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
2    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
3    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
4    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

   144  145  146  147  148  149  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    0  
4    0    0    0    0    0    0  

[5 rows x 150 columns]

In [41]:
(computers.sum(axis = 1) > 0).mean()

0.1804

In [42]:
#How likely is it that 450 students all download anaconda without an issue?

download_p_fail = 1/250
download_p_pass = 249/250
choice = [0,1]
sample = 450
n_sim = 10_000
array = np.random.choice(choice,p=[download_p_pass,download_p_fail],size = (n_sim, sample))
anaconda_installation = pd.DataFrame(array)
anaconda_installation.head()

0    1    2    3    4    5    6    7    8    9    ...  440  441  442  443  \
0    0    1    0    0    0    0    0    0    0    0  ...    0    0    0    0   
1    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
2    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
3    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
4    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

   444  445  446  447  448  449  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    0  
4    0    0    0    0    0    0  

[5 rows x 450 columns]

In [43]:
(computers.sum(axis = 1) == 0).mean()

0.8196

In [ ]:
#conclusion
#when there is no dowloading issue from any students that means sum = 0

In [152]:
# 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park.
#However, you haven't seen a food truck there in 3 days. How unlikely is this?

#How likely is it that a food truck will show up sometime this week?

days = range(7)
simulations = 1000
foodtruck = 1
chance = 70

random_days = np.random.choice(days,(simulations,foodtruck))<= foodtruck - 3


days_df=(pd.DataFrame(random_days))


days_df.head()

0
0  False
1  False
2  False
3  False
4  False

In [123]:
# 8. If 23 people are in the same room, what are the odds that two of them share a birthday? 

bdays = range(365)
simulations = 1000
students = 23

random_bdays = np.random.choice(bdays,(simulations,students))


bday_df=(pd.DataFrame(random_bdays))

bday_df.head()


0    1    2    3    4    5    6    7    8    9   ...   13   14   15   16  \
0   72  361   21  123   39  307   63  274   14  142  ...  185  200  216  359   
1  308  105  282  191  263  197   53   10  244  257  ...  184  155   79  364   
2   74  119  283  265  190  360  223  132  131  349  ...  315  339  188  249   
3  232  119  134  135  233   31  181  343  188  283  ...  361  324  343  157   
4   63  180   29  165  362   88  212   70  299  201  ...  249   54   99  263   

    17   18   19   20   21   22  
0  341  341  220  272  145  187  
1  346   67   45    4  308   92  
2  143  181    6  268   16  306  
3   35   43  313   49  271  168  
4  325  158  354   87   69  111  

[5 rows x 23 columns]

In [126]:
bday_df.nunique(axis=1)

0      22
1      22
2      23
3      22
4      23
       ..
995    21
996    23
997    21
998    23
999    22
Length: 1000, dtype: int64

In [ ]:
(bday_df.nunique(axis=1)<students)

In [129]:
# What if it's 20 people? 40?

bdays = range(365)
simulations = 1000
students = 20

random_bdays = np.random.choice(bdays,(simulations,students))


bday_df=(pd.DataFrame(random_bdays))

bday_df.head()

0    1    2    3    4    5    6    7    8    9    10   11   12   13   14  \
0  284  333    8   38   55  325  258  167  232  219  138   71  202  111  111   
1  311  127  292   57  121   37  110  277   94   59  201  147  104  214  120   
2  176  330  104  106  144  362  207  216  176   79  358  239  116  257  331   
3  335  297   82  129   84  247  237  129   71   93   65  305  343  128  320   
4  110  184   54  280   14  285  178  230   97  265  338  310   40  134  251   

    15   16   17   18   19  
0  148   69  104  274  136  
1  317  118  319  318  342  
2  215   72  125  327  311  
3   69  151   17    1   72  
4   76  229  344  328  190

In [130]:
bday_df.nunique(axis=1)

0      19
1      20
2      19
3      19
4      20
       ..
995    19
996    20
997    20
998    20
999    20
Length: 1000, dtype: int64

In [131]:
(bday_df.nunique(axis=1)<students)

0       True
1      False
2       True
3       True
4      False
       ...  
995     True
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool